### ISSUE TITLE
个人搭建

### ISSUE THREAD

**Issue by crazyn2** [1061700625/RemoteFileTransfer#4]
如果是个人搭建，还需要公网地址吧。请问你是怎么解决学校实验室上运行的服务与个人连接的问题，似乎没有公网地址无法直接连接，中间还需要一个有公网地址的服务器作为跳板

**Comment by 1061700625** [comment]
用一个服务器做中继就好了，用的mqtt协议------------------ 原始邮件 ------------------
发件人: "crazyn2"<notifications@github.com>
发送时间: 2020年4月14日(星期二) 中午1:46
收件人: "1061700625/RemoteFileTransfer"<RemoteFileTransfer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [1061700625/RemoteFileTransfer] 个人搭建 (#4)




 
如果是个人搭建，还需要公网地址吧。请问你是怎么解决学校实验室上运行的&#x670D;务与个人连接的问题，似乎没有公网地址无法直接连接，中间还需要一个有公网地址的&#x670D;务器作为跳板
 
&mdash;

**Comment by 1061700625** [comment]
还有一种办法，是FRP+SS，直接用实验室的网做代理，我试过成功了。不过也得有个服务器做中继。------------------ 原始邮件 ------------------
发件人: "crazyn2"<notifications@github.com>
发送时间: 2020年4月14日(星期二) 中午1:46
收件人: "1061700625/RemoteFileTransfer"<RemoteFileTransfer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [1061700625/RemoteFileTransfer] 个人搭建 (#4)




 
如果是个人搭建，还需要公网地址吧。请问你是怎么解决学校实验室上运行的&#x670D;务与个人连接的问题，似乎没有公网地址无法直接连接，中间还需要一个有公网地址的&#x670D;务器作为跳板
 
&mdash;

**Comment by crazyn2** [comment]
请问你的详细步骤是怎么样的啊

**Comment by 1061700625** [comment]
https://mp.weixin.qq.com/s?__biz=MzU5MDE1NTA3Nw==&mid=2247483951&idx=1&sn=7e6f1802ad82f0ee89e7026d0ec3e961&chksm=fdc3de05cab45713dfc2470a92e7934d54a9447db7a0c8e7411287e943550a86eddd37d56e32&token=236455199&lang=zh_CN#rd

**Comment by crazyn2** [comment]
多谢，我回学校的时候试试


| |
brazyn
|
|
邮箱：13868637093@163.com
|

Signature is customized by Netease Mail Master

在2020年04月14日 15:21，SXF 写道：

https://mp.weixin.qq.com/s?__biz=MzU5MDE1NTA3Nw==&mid=2247483951&idx=1&sn=7e6f1802ad82f0ee89e7026d0ec3e961&chksm=fdc3de05cab45713dfc2470a92e7934d54a9447db7a0c8e7411287e943550a86eddd37d56e32&token=236455199&lang=zh_CN#rd
